services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - Ft_network

  logstash:
    image: docker.elastic.co/logstash/logstash:8.17.3
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    expose:
      - "5000"
      - "5044"
    networks:
      - Ft_network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.3
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - Ft_network

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.17.3
    container_name: filebeat
    user: root  # This allows Filebeat to read logs from the host
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log/:/var/log/:ro
      - filebeat_data:/usr/share/filebeat/data
    command: filebeat -e --strict.perms=false
    depends_on:
      - elasticsearch
      - logstash
    networks:
      - Ft_network

volumes:
  esdata:
    driver: local
  filebeat_data:
    driver: local

networks:
  Ft_network:
    driver: bridge
